apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  # Service of type nodeport
  type: NodePort
  # The deafult port for postgres
  ports:
    - port: 5432
