apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: admission.webhook.container.training
webhooks:
- name: admission.webhook.container.training
  rules:
  - apiGroups:   [""]
    apiVersions: ["v1"]
    operations:  ["CREATE", "UPDATE"]
    resources:   ["pods"]
    scope:       "Namespaced"
  clientConfig:
    #service:
    #  namespace: webhooks
    #  name: admission
    #caBundle: ""
    #url: https://xxxxyyyyzzzz.ngrok.io
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Ignore # defaults to Fail
