apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Set the default namespace for all the resources
namespace: wp-demo

# The files to be processed
# Kustomization will re-order the kinds if required
bases:
   - /resources/MySQL
   - /resources/Wordpress

resources:
   - Namespace.yaml

# kubectl expose rc \
#    example \
#    --port=8765 \
#    --target-port=9376 \
#    -name=example-service \
#    --type=LoadBalancer