kind: Service
apiVersion: v1
metadata:
  name: certbot
spec:
  ports:
  - port: 80
    protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: certbot
spec:
  rules:
  - http:
      paths:
      - path: /.well-known/acme-challenge/
        pathType: Prefix
        backend:
          service:
            name: certbot
            port:
              number: 80
---
apiVersion: v1
kind: Endpoints
metadata:
  name: certbot
subsets:
- addresses:
  - ip: A.B.C.D
  ports:
  - port: 8000
    protocol: TCP

