---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jean.doe
  namespace: users
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: user=jean.doe
rules:
- apiGroups: [ certificates.k8s.io ]
  resources: [ certificatesigningrequests ]
  verbs:     [ create ]
- apiGroups:     [ certificates.k8s.io ]
  resourceNames: [ user=jean.doe ]
  resources:     [ certificatesigningrequests ]
  verbs:         [ get, create, delete, watch ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: user=jean.doe
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: user=jean.doe
subjects:
- kind: ServiceAccount
  name: jean.doe
  namespace: users

