# NOTE:
#       The service account `default:default` already exists in k8s cluster when the cluster is created.
#       In this sample we will create a default user under our namespace
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: test
