# kustomization.yaml for ConfigMap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Generate config file from file
configMapGenerator:
  - name: configFromFile
    files:
    - .env
#
# Optional flag to mark if we want hashed suffix or not
#
#generatorOptions:
#  disableNameSuffixHash: true  