apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor-app
spec:
  selector:
    matchLabels:
      app: monitor-app
  template:
    metadata:
      labels:
        app: monitor-app
    spec:
      containers:
      - name: monitor-app
        image: nirgeier/monitor-app
        args:
        - sleep
        - "86400"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
