apiVersion: v1
kind: Service
metadata:
  labels:
    app: postgres
    author: nirgeier@gmail.com
    env: codeWizard-cluster
    version: v1
  name: postgres
  namespace: codewizard
spec:
  ports:
  - port: 5432
  selector:
    app: postgres
    author: nirgeier@gmail.com
    env: codeWizard-cluster
    version: v1
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    author: nirgeier@gmail.com
    env: codeWizard-cluster
    version: v1
  name: myapp
  namespace: codewizard
spec:
  selector:
    matchLabels:
      app: myapp
      author: nirgeier@gmail.com
      env: codeWizard-cluster
      version: v1
  template:
    metadata:
      labels:
        app: myapp
        author: nirgeier@gmail.com
        env: codeWizard-cluster
        version: v1
    spec:
      containers:
      - image: __image__
        name: myapp
      - image: nginx
        name: nginx
