# kustomization.yaml for ConfigMap
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  # Generate config file from env file
  - name: configMapFromEnv
    env: .env
#
# Optional flag to mark if we want hashed suffix or not
#
#generatorOptions:
#  disableNameSuffixHash: true