# The required apiVersion for the CRD
apiVersion: apiextensions.k8s.io/v1

# The Kind is: 'CustomResourceDefinition'
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  # In this sample we define the name <codewizard> & group: <codewizard.co.il>
  # Refer to the `spec.names` below
  name: custom-crd.codewizard.co.il
spec:
  # The CRD can be applied to either Namespaced or Cluster
  # In this case we set it to Name
  scope: Namespaced

  # group name to use for REST API: /apis/<group>/<version>
  # same group as defined under `metadata.name`
  group: codewizard.co.il

  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: custom-crd
    # singular name to be used as an alias on the CLI and for display
    singular: cwcrd
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CodeWizardCRD
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
      - cwcrd

  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          required: ["spec"]
          type: object
          # The properties which be defined under the `spec`
          properties:
            spec:
              type: object
              # The properties which can be defined and their type
              properties:
                crdSpec:
                  type: string
                image:
                  type: string
                replicas:
                  type: integer
