apiVersion: v1
kind: Service
metadata:
  name: webserverv2
spec:
  ports:
    - name: http-web
      port: 80
      protocol: TCP
      targetPort: 5050
  selector:
    app: webserver
    version: v2
