# customize your cluster size, your cards template, and the versions

# Number of VMs per cluster
clustersize: 3

# The hostname of each node will be clusterprefix + a number
clusterprefix: node

# Jinja2 template to use to generate ready-to-cut cards
cards_template: cards.html

# Use "Letter" in the US, and "A4" everywhere else
paper_size: Letter

# Login and password that students will use
user_login: docker
user_password: training
