apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# We assume since we are build upon demo 01 - we already have the namespace
namespace: codewizard

resources:
  - resources/web-server1-network-faults.yaml
  #- resources/web-server1-network-faults.yaml
