apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: postgres
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  $patch: replace
  # Replace the current ports with port 80
  ports:
    - port: 80